# Toy config file
name: germany-summarizer
wandb_data_path: germany-dataset:latest/germany-dataset.csv
shorten: true
policy: C1E_School closing
tools:
  - analyst
  - historian
  - summarizer
  - tools